// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcNniIwsdMY8f_xrKwCO3QEY8ETYiDdz0',
    appId: '1:738424821612:web:af4538a5e95d47fc8ec549',
    messagingSenderId: '738424821612',
    projectId: 'finder-c40c4',
    authDomain: 'finder-c40c4.firebaseapp.com',
    storageBucket: 'finder-c40c4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeXESRrtXpQSy86QRQwY-c2THPkaJhQxc',
    appId: '1:738424821612:android:3ec1cab4a11f6af88ec549',
    messagingSenderId: '738424821612',
    projectId: 'finder-c40c4',
    storageBucket: 'finder-c40c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1BIpVhsWo-DGRljJwzzS30jaucacNPzs',
    appId: '1:738424821612:ios:0dc6b917788973948ec549',
    messagingSenderId: '738424821612',
    projectId: 'finder-c40c4',
    storageBucket: 'finder-c40c4.firebasestorage.app',
    iosBundleId: 'com.example.finder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1BIpVhsWo-DGRljJwzzS30jaucacNPzs',
    appId: '1:738424821612:ios:0dc6b917788973948ec549',
    messagingSenderId: '738424821612',
    projectId: 'finder-c40c4',
    storageBucket: 'finder-c40c4.firebasestorage.app',
    iosBundleId: 'com.example.finder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcNniIwsdMY8f_xrKwCO3QEY8ETYiDdz0',
    appId: '1:738424821612:web:4568a17fb518c4088ec549',
    messagingSenderId: '738424821612',
    projectId: 'finder-c40c4',
    authDomain: 'finder-c40c4.firebaseapp.com',
    storageBucket: 'finder-c40c4.firebasestorage.app',
  );
}
